"use server";

import { db } from "@/db/drizzle";
import {
	tasks,
	cases,
	caseStages,
	caseStageGroups,
	users,
} from "@/db/schema";
import { requireSession } from "@/lib/auth/session";
import {
	eq,
	and,
	isNull,
	desc,
	asc,
	lte,
	gte,
	count,
	sql,
	ne,
} from "drizzle-orm";
import { revalidatePath } from "next/cache";

export type TaskFilters = {
	status?: string;
	priority?: string;
	dueDateRange?: "overdue" | "today" | "this_week" | "next_week" | "no_date";
};

/**
 * Get the current user's task queue.
 */
export async function getMyQueue(filters: TaskFilters = {}) {
	const session = await requireSession();
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const tomorrow = new Date(today);
	tomorrow.setDate(tomorrow.getDate() + 1);
	const endOfWeek = new Date(today);
	endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
	const endOfNextWeek = new Date(endOfWeek);
	endOfNextWeek.setDate(endOfNextWeek.getDate() + 7);

	const conditions = [
		eq(tasks.assignedToId, session.id),
		isNull(tasks.deletedAt),
	];

	if (filters.status) {
		conditions.push(
			eq(
				tasks.status,
				filters.status as
					| "pending"
					| "in_progress"
					| "completed"
					| "skipped"
					| "blocked",
			),
		);
	} else {
		// Default: show non-completed tasks
		conditions.push(ne(tasks.status, "completed"));
		conditions.push(ne(tasks.status, "skipped"));
	}

	if (filters.dueDateRange === "overdue") {
		conditions.push(lte(tasks.dueDate, now));
	} else if (filters.dueDateRange === "today") {
		conditions.push(gte(tasks.dueDate, today));
		conditions.push(lte(tasks.dueDate, tomorrow));
	} else if (filters.dueDateRange === "this_week") {
		conditions.push(gte(tasks.dueDate, today));
		conditions.push(lte(tasks.dueDate, endOfWeek));
	} else if (filters.dueDateRange === "next_week") {
		conditions.push(gte(tasks.dueDate, endOfWeek));
		conditions.push(lte(tasks.dueDate, endOfNextWeek));
	} else if (filters.dueDateRange === "no_date") {
		conditions.push(isNull(tasks.dueDate));
	}

	const result = await db
		.select({
			id: tasks.id,
			title: tasks.title,
			description: tasks.description,
			status: tasks.status,
			priority: tasks.priority,
			dueDate: tasks.dueDate,
			isAutoGenerated: tasks.isAutoGenerated,
			caseId: tasks.caseId,
			caseNumber: cases.caseNumber,
			stageName: caseStages.name,
			stageCode: caseStages.code,
			stageGroupColor: caseStageGroups.color,
			createdAt: tasks.createdAt,
		})
		.from(tasks)
		.innerJoin(cases, eq(tasks.caseId, cases.id))
		.leftJoin(caseStages, eq(cases.currentStageId, caseStages.id))
		.leftJoin(
			caseStageGroups,
			eq(caseStages.stageGroupId, caseStageGroups.id),
		)
		.where(and(...conditions))
		.orderBy(asc(tasks.dueDate), desc(tasks.priority));

	return result;
}

/**
 * Get queue counts for tab badges.
 */
export async function getQueueCounts() {
	const session = await requireSession();
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const tomorrow = new Date(today);
	tomorrow.setDate(tomorrow.getDate() + 1);
	const endOfWeek = new Date(today);
	endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
	const endOfNextWeek = new Date(endOfWeek);
	endOfNextWeek.setDate(endOfNextWeek.getDate() + 7);

	const baseConditions = [
		eq(tasks.assignedToId, session.id),
		isNull(tasks.deletedAt),
		ne(tasks.status, "completed"),
		ne(tasks.status, "skipped"),
	];

	const [allResult, overdueResult, todayResult, weekResult, nextWeekResult, noDateResult] =
		await Promise.all([
			db
				.select({ count: count() })
				.from(tasks)
				.where(and(...baseConditions)),
			db
				.select({ count: count() })
				.from(tasks)
				.where(and(...baseConditions, lte(tasks.dueDate, now))),
			db
				.select({ count: count() })
				.from(tasks)
				.where(
					and(
						...baseConditions,
						gte(tasks.dueDate, today),
						lte(tasks.dueDate, tomorrow),
					),
				),
			db
				.select({ count: count() })
				.from(tasks)
				.where(
					and(
						...baseConditions,
						gte(tasks.dueDate, today),
						lte(tasks.dueDate, endOfWeek),
					),
				),
			db
				.select({ count: count() })
				.from(tasks)
				.where(
					and(
						...baseConditions,
						gte(tasks.dueDate, endOfWeek),
						lte(tasks.dueDate, endOfNextWeek),
					),
				),
			db
				.select({ count: count() })
				.from(tasks)
				.where(and(...baseConditions, isNull(tasks.dueDate))),
		]);

	return {
		all: allResult[0]?.count ?? 0,
		overdue: overdueResult[0]?.count ?? 0,
		today: todayResult[0]?.count ?? 0,
		thisWeek: weekResult[0]?.count ?? 0,
		nextWeek: nextWeekResult[0]?.count ?? 0,
		noDate: noDateResult[0]?.count ?? 0,
	};
}

/**
 * Complete a task.
 */
export async function completeTask(taskId: string) {
	const session = await requireSession();
	await db
		.update(tasks)
		.set({
			status: "completed",
			completedAt: new Date(),
			completedBy: session.id,
			updatedAt: new Date(),
		})
		.where(eq(tasks.id, taskId));

	// Unblock dependent tasks
	const dependentTasks = await db
		.select({ id: tasks.id })
		.from(tasks)
		.where(
			and(eq(tasks.dependsOnTaskId, taskId), eq(tasks.status, "blocked")),
		);

	for (const dep of dependentTasks) {
		await db
			.update(tasks)
			.set({ status: "pending", updatedAt: new Date() })
			.where(eq(tasks.id, dep.id));
	}

	revalidatePath("/queue");
}

/**
 * Bulk complete tasks.
 */
export async function bulkCompleteTasks(taskIds: string[]) {
	await requireSession();
	for (const taskId of taskIds) {
		await completeTask(taskId);
	}
	revalidatePath("/queue");
}

/**
 * Create a manual task.
 */
export async function createTask(data: {
	caseId: string;
	title: string;
	description?: string;
	priority?: string;
	assignedToId?: string;
	dueDate?: string;
}) {
	const session = await requireSession();
	const [caseRow] = await db
		.select({ organizationId: cases.organizationId })
		.from(cases)
		.where(eq(cases.id, data.caseId));

	if (!caseRow) throw new Error("Case not found");

	const [newTask] = await db
		.insert(tasks)
		.values({
			organizationId: caseRow.organizationId,
			caseId: data.caseId,
			title: data.title,
			description: data.description,
			priority: (data.priority ?? "medium") as
				| "low"
				| "medium"
				| "high"
				| "urgent",
			assignedToId: data.assignedToId ?? session.id,
			dueDate: data.dueDate ? new Date(data.dueDate) : null,
			createdBy: session.id,
		})
		.returning();

	revalidatePath("/queue");
	revalidatePath(`/cases/${data.caseId}`);
	return newTask;
}

/**
 * Get tasks for a specific case.
 */
export async function getCaseTasks(caseId: string) {
	const result = await db
		.select({
			id: tasks.id,
			title: tasks.title,
			description: tasks.description,
			status: tasks.status,
			priority: tasks.priority,
			dueDate: tasks.dueDate,
			completedAt: tasks.completedAt,
			isAutoGenerated: tasks.isAutoGenerated,
			assignedToId: tasks.assignedToId,
			assigneeName: sql<string>`concat(${users.firstName}, ' ', ${users.lastName})`,
			createdAt: tasks.createdAt,
		})
		.from(tasks)
		.leftJoin(users, eq(tasks.assignedToId, users.id))
		.where(and(eq(tasks.caseId, caseId), isNull(tasks.deletedAt)))
		.orderBy(asc(tasks.status), asc(tasks.dueDate));

	return result;
}

/**
 * Get count of tasks due today for dashboard.
 */
export async function getTasksDueTodayCount() {
	const session = await requireSession();
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const tomorrow = new Date(today);
	tomorrow.setDate(tomorrow.getDate() + 1);

	const [result] = await db
		.select({ count: count() })
		.from(tasks)
		.where(
			and(
				eq(tasks.assignedToId, session.id),
				ne(tasks.status, "completed"),
				ne(tasks.status, "skipped"),
				isNull(tasks.deletedAt),
				gte(tasks.dueDate, today),
				lte(tasks.dueDate, tomorrow),
			),
		);

	return result?.count ?? 0;
}

/**
 * Get overdue tasks count.
 */
export async function getOverdueTaskCount() {
	const session = await requireSession();
	const [result] = await db
		.select({ count: count() })
		.from(tasks)
		.where(
			and(
				eq(tasks.assignedToId, session.id),
				ne(tasks.status, "completed"),
				ne(tasks.status, "skipped"),
				isNull(tasks.deletedAt),
				lte(tasks.dueDate, new Date()),
			),
		);
	return result?.count ?? 0;
}
