"use server";

import { db } from "@/db/drizzle";
import {
  tasks,
  cases,
  caseStages,
  caseStageGroups,
  users,
  workflowTemplates,
} from "@/db/schema";
import { requireSession } from "@/lib/auth/session";
import {
  eq,
  and,
  isNull,
  desc,
  asc,
  lte,
  gte,
  count,
  sql,
  ne,
} from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { logger } from "@/lib/logger/server";

export type TaskFilters = {
  status?: string;
  priority?: string;
  dueDateRange?: "overdue" | "today" | "this_week" | "next_week" | "no_date";
};

/**
 * Hard cap on how many rows any queue query will return. Filing agents need
 * sub-300ms responses and nobody productively scrolls past a few hundred tasks
 * in a single view — use filtering/pagination to drill down instead of
 * dumping the entire table.
 */
const DEFAULT_QUEUE_LIMIT = 200;
const TEAM_QUEUE_LIMIT = 500;

/**
 * Get the current user's task queue.
 */
export async function getMyQueue(
  filters: TaskFilters = {},
  limit: number = DEFAULT_QUEUE_LIMIT,
) {
  const session = await requireSession();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const endOfWeek = new Date(today);
  endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
  const endOfNextWeek = new Date(endOfWeek);
  endOfNextWeek.setDate(endOfNextWeek.getDate() + 7);

  const conditions = [
    eq(tasks.assignedToId, session.id),
    isNull(tasks.deletedAt),
  ];

  if (filters.status) {
    conditions.push(
      eq(
        tasks.status,
        filters.status as
          | "pending"
          | "in_progress"
          | "completed"
          | "skipped"
          | "blocked",
      ),
    );
  } else {
    // Default: show non-completed tasks
    conditions.push(ne(tasks.status, "completed"));
    conditions.push(ne(tasks.status, "skipped"));
  }

  if (filters.dueDateRange === "overdue") {
    conditions.push(lte(tasks.dueDate, now));
  } else if (filters.dueDateRange === "today") {
    conditions.push(gte(tasks.dueDate, today));
    conditions.push(lte(tasks.dueDate, tomorrow));
  } else if (filters.dueDateRange === "this_week") {
    conditions.push(gte(tasks.dueDate, today));
    conditions.push(lte(tasks.dueDate, endOfWeek));
  } else if (filters.dueDateRange === "next_week") {
    conditions.push(gte(tasks.dueDate, endOfWeek));
    conditions.push(lte(tasks.dueDate, endOfNextWeek));
  } else if (filters.dueDateRange === "no_date") {
    conditions.push(isNull(tasks.dueDate));
  }

  const result = await db
    .select({
      id: tasks.id,
      title: tasks.title,
      description: tasks.description,
      status: tasks.status,
      priority: tasks.priority,
      dueDate: tasks.dueDate,
      isAutoGenerated: tasks.isAutoGenerated,
      caseId: tasks.caseId,
      caseNumber: cases.caseNumber,
      stageName: caseStages.name,
      stageCode: caseStages.code,
      stageGroupColor: caseStageGroups.color,
      createdAt: tasks.createdAt,
    })
    .from(tasks)
    .innerJoin(cases, eq(tasks.caseId, cases.id))
    .leftJoin(caseStages, eq(cases.currentStageId, caseStages.id))
    .leftJoin(caseStageGroups, eq(caseStages.stageGroupId, caseStageGroups.id))
    .where(and(...conditions))
    .orderBy(asc(tasks.dueDate), desc(tasks.priority))
    .limit(limit);

  return result;
}

/**
 * Get queue counts for tab badges.
 */
export async function getQueueCounts() {
  const session = await requireSession();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const endOfWeek = new Date(today);
  endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
  const endOfNextWeek = new Date(endOfWeek);
  endOfNextWeek.setDate(endOfNextWeek.getDate() + 7);

  const baseConditions = [
    eq(tasks.assignedToId, session.id),
    isNull(tasks.deletedAt),
    ne(tasks.status, "completed"),
    ne(tasks.status, "skipped"),
  ];

  const [
    allResult,
    overdueResult,
    todayResult,
    weekResult,
    nextWeekResult,
    noDateResult,
  ] = await Promise.all([
    db
      .select({ count: count() })
      .from(tasks)
      .where(and(...baseConditions)),
    db
      .select({ count: count() })
      .from(tasks)
      .where(and(...baseConditions, lte(tasks.dueDate, now))),
    db
      .select({ count: count() })
      .from(tasks)
      .where(
        and(
          ...baseConditions,
          gte(tasks.dueDate, today),
          lte(tasks.dueDate, tomorrow),
        ),
      ),
    db
      .select({ count: count() })
      .from(tasks)
      .where(
        and(
          ...baseConditions,
          gte(tasks.dueDate, today),
          lte(tasks.dueDate, endOfWeek),
        ),
      ),
    db
      .select({ count: count() })
      .from(tasks)
      .where(
        and(
          ...baseConditions,
          gte(tasks.dueDate, endOfWeek),
          lte(tasks.dueDate, endOfNextWeek),
        ),
      ),
    db
      .select({ count: count() })
      .from(tasks)
      .where(and(...baseConditions, isNull(tasks.dueDate))),
  ]);

  return {
    all: allResult[0]?.count ?? 0,
    overdue: overdueResult[0]?.count ?? 0,
    today: todayResult[0]?.count ?? 0,
    thisWeek: weekResult[0]?.count ?? 0,
    nextWeek: nextWeekResult[0]?.count ?? 0,
    noDate: noDateResult[0]?.count ?? 0,
  };
}

/**
 * Complete a task.
 * After completion, unblocks dependent tasks and checks if all workflow tasks
 * for the case's current stage are now complete. If so, auto-advances the case
 * to the next stage (by display order).
 */
export async function completeTask(taskId: string) {
  const session = await requireSession();
  await db
    .update(tasks)
    .set({
      status: "completed",
      completedAt: new Date(),
      completedBy: session.id,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, taskId));

  // Unblock dependent tasks in a single UPDATE instead of N round-trips.
  await db
    .update(tasks)
    .set({ status: "pending", updatedAt: new Date() })
    .where(
      and(eq(tasks.dependsOnTaskId, taskId), eq(tasks.status, "blocked")),
    );

  // Auto-advance: check if all workflow tasks for this case's current stage are done
  await checkAndAutoAdvance(taskId, session.id, session.organizationId);

  revalidatePath("/queue");
}

/**
 * Check if all workflow-generated tasks for a case's current stage are complete,
 * and if so auto-advance to the next stage.
 */
async function checkAndAutoAdvance(
  completedTaskId: string,
  userId: string,
  organizationId: string,
) {
  // Get the completed task to find which case and workflow it belongs to
  const [completedTask] = await db
    .select({
      caseId: tasks.caseId,
      workflowTemplateId: tasks.workflowTemplateId,
    })
    .from(tasks)
    .where(eq(tasks.id, completedTaskId));

  if (!completedTask?.workflowTemplateId) return; // Not a workflow task

  // Get the workflow's trigger stage
  const [workflow] = await db
    .select({ triggerStageId: workflowTemplates.triggerStageId })
    .from(workflowTemplates)
    .where(eq(workflowTemplates.id, completedTask.workflowTemplateId));

  if (!workflow?.triggerStageId) return;

  // Verify the case is still on the workflow's trigger stage
  const [caseRow] = await db
    .select({ currentStageId: cases.currentStageId })
    .from(cases)
    .where(eq(cases.id, completedTask.caseId));

  if (!caseRow || caseRow.currentStageId !== workflow.triggerStageId) return;

  // Check if ALL workflow tasks for this case + workflow are complete
  const [pendingCount] = await db
    .select({ count: count() })
    .from(tasks)
    .where(
      and(
        eq(tasks.caseId, completedTask.caseId),
        eq(tasks.workflowTemplateId, completedTask.workflowTemplateId),
        ne(tasks.status, "completed"),
        ne(tasks.status, "skipped"),
        isNull(tasks.deletedAt),
      ),
    );

  if ((pendingCount?.count ?? 0) > 0) return; // Still tasks remaining

  // All tasks complete -- determine next stage by display order
  const [currentStage] = await db
    .select({
      displayOrder: caseStages.displayOrder,
      stageGroupId: caseStages.stageGroupId,
      allowedNextStageIds: caseStages.allowedNextStageIds,
      organizationId: caseStages.organizationId,
    })
    .from(caseStages)
    .where(eq(caseStages.id, caseRow.currentStageId));

  if (!currentStage) return;

  // If the stage has explicit allowed next stages, pick the first one
  // Otherwise, pick the next stage by display order
  let nextStageId: string | null = null;

  if (
    currentStage.allowedNextStageIds &&
    currentStage.allowedNextStageIds.length > 0
  ) {
    nextStageId = currentStage.allowedNextStageIds[0];
  } else {
    // Get the next stage by display order across all groups
    const allStages = await db
      .select({
        id: caseStages.id,
        displayOrder: caseStages.displayOrder,
        groupDisplayOrder: caseStageGroups.displayOrder,
      })
      .from(caseStages)
      .innerJoin(
        caseStageGroups,
        eq(caseStages.stageGroupId, caseStageGroups.id),
      )
      .where(
        and(
          eq(caseStages.organizationId, currentStage.organizationId),
          isNull(caseStages.deletedAt),
        ),
      )
      .orderBy(asc(caseStageGroups.displayOrder), asc(caseStages.displayOrder));

    const currentIdx = allStages.findIndex(
      (s) => s.id === caseRow.currentStageId,
    );
    if (currentIdx >= 0 && currentIdx < allStages.length - 1) {
      nextStageId = allStages[currentIdx + 1].id;
    }
  }

  if (!nextStageId) return; // No next stage (terminal)

  // Auto-advance the case
  const { changeCaseStage } = await import("@/app/actions/cases");
  await changeCaseStage({
    caseId: completedTask.caseId,
    newStageId: nextStageId,
    notes: "Auto-advanced: all workflow tasks completed",
  });

  logger.info("Auto-advanced case stage", {
    caseId: completedTask.caseId,
    fromStageId: caseRow.currentStageId,
    toStageId: nextStageId,
    workflowTemplateId: completedTask.workflowTemplateId,
  });
}

/**
 * Bulk complete tasks.
 */
export async function bulkCompleteTasks(taskIds: string[]) {
  await requireSession();
  // Run task completions in parallel — each completion is idempotent and
  // auto-advance checks are safe to race because the workflow-engine caller
  // re-reads state before mutating.
  await Promise.all(taskIds.map((taskId) => completeTask(taskId)));
  revalidatePath("/queue");
}

/**
 * Create a manual task.
 */
export async function createTask(data: {
  caseId: string;
  title: string;
  description?: string;
  priority?: string;
  assignedToId?: string;
  dueDate?: string;
}) {
  const session = await requireSession();
  const [caseRow] = await db
    .select({ organizationId: cases.organizationId })
    .from(cases)
    .where(eq(cases.id, data.caseId));

  if (!caseRow) throw new Error("Case not found");

  const [newTask] = await db
    .insert(tasks)
    .values({
      organizationId: caseRow.organizationId,
      caseId: data.caseId,
      title: data.title,
      description: data.description,
      priority: (data.priority ?? "medium") as
        | "low"
        | "medium"
        | "high"
        | "urgent",
      assignedToId: data.assignedToId ?? session.id,
      dueDate: data.dueDate ? new Date(data.dueDate) : null,
      createdBy: session.id,
    })
    .returning();

  revalidatePath("/queue");
  revalidatePath(`/cases/${data.caseId}`);
  return newTask;
}

/**
 * Get tasks for a specific case.
 */
export async function getCaseTasks(caseId: string) {
  const result = await db
    .select({
      id: tasks.id,
      title: tasks.title,
      description: tasks.description,
      status: tasks.status,
      priority: tasks.priority,
      dueDate: tasks.dueDate,
      completedAt: tasks.completedAt,
      isAutoGenerated: tasks.isAutoGenerated,
      assignedToId: tasks.assignedToId,
      assigneeName: sql<string>`concat(${users.firstName}, ' ', ${users.lastName})`,
      createdAt: tasks.createdAt,
    })
    .from(tasks)
    .leftJoin(users, eq(tasks.assignedToId, users.id))
    .where(and(eq(tasks.caseId, caseId), isNull(tasks.deletedAt)))
    .orderBy(asc(tasks.status), asc(tasks.dueDate))
    .limit(500);

  return result;
}

/**
 * Get count of tasks due today for dashboard.
 */
export async function getTasksDueTodayCount() {
  const session = await requireSession();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  const [result] = await db
    .select({ count: count() })
    .from(tasks)
    .where(
      and(
        eq(tasks.assignedToId, session.id),
        ne(tasks.status, "completed"),
        ne(tasks.status, "skipped"),
        isNull(tasks.deletedAt),
        gte(tasks.dueDate, today),
        lte(tasks.dueDate, tomorrow),
      ),
    );

  return result?.count ?? 0;
}

/**
 * Get overdue tasks count.
 */
export async function getOverdueTaskCount() {
  const session = await requireSession();
  const [result] = await db
    .select({ count: count() })
    .from(tasks)
    .where(
      and(
        eq(tasks.assignedToId, session.id),
        ne(tasks.status, "completed"),
        ne(tasks.status, "skipped"),
        isNull(tasks.deletedAt),
        lte(tasks.dueDate, new Date()),
      ),
    );
  return result?.count ?? 0;
}

/**
 * Get team queue: all tasks for users on the same team as the current user.
 * Only accessible by managers (case_manager) and admins.
 */
export async function getTeamQueue(limit: number = TEAM_QUEUE_LIMIT) {
  const session = await requireSession();

  // Only managers and admins can view team queue
  if (session.role !== "admin" && session.role !== "case_manager") {
    throw new Error(
      "Unauthorized: only managers and admins can view team queue",
    );
  }

  const result = await db
    .select({
      id: tasks.id,
      title: tasks.title,
      description: tasks.description,
      status: tasks.status,
      priority: tasks.priority,
      dueDate: tasks.dueDate,
      isAutoGenerated: tasks.isAutoGenerated,
      caseId: tasks.caseId,
      caseNumber: cases.caseNumber,
      stageName: caseStages.name,
      stageCode: caseStages.code,
      stageGroupColor: caseStageGroups.color,
      createdAt: tasks.createdAt,
      assignedToId: tasks.assignedToId,
      assigneeName: sql<string>`concat(${users.firstName}, ' ', ${users.lastName})`,
    })
    .from(tasks)
    .innerJoin(cases, eq(tasks.caseId, cases.id))
    .leftJoin(caseStages, eq(cases.currentStageId, caseStages.id))
    .leftJoin(caseStageGroups, eq(caseStages.stageGroupId, caseStageGroups.id))
    .leftJoin(users, eq(tasks.assignedToId, users.id))
    .where(
      and(
        isNull(tasks.deletedAt),
        ne(tasks.status, "completed"),
        ne(tasks.status, "skipped"),
        session.team
          ? eq(
              users.team,
              session.team as
                | "intake"
                | "filing"
                | "medical_records"
                | "mail_sorting"
                | "case_management"
                | "hearings"
                | "administration",
            )
          : eq(tasks.organizationId, session.organizationId),
      ),
    )
    .orderBy(asc(tasks.dueDate), desc(tasks.priority))
    .limit(limit);

  return result;
}

/**
 * Reassign a task to a different user.
 */
export async function reassignTask(taskId: string, assignToUserId: string) {
  await requireSession();
  await db
    .update(tasks)
    .set({
      assignedToId: assignToUserId,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, taskId));

  revalidatePath("/queue");
}

/**
 * Snooze a task by updating its due date.
 */
export async function snoozeTask(taskId: string, newDueDate: string) {
  await requireSession();
  await db
    .update(tasks)
    .set({
      dueDate: new Date(newDueDate),
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, taskId));

  revalidatePath("/queue");
}

/**
 * Get organization users for reassignment picker.
 */
export async function getOrgUsers() {
  const session = await requireSession();
  const result = await db
    .select({
      id: users.id,
      firstName: users.firstName,
      lastName: users.lastName,
      email: users.email,
      role: users.role,
      team: users.team,
    })
    .from(users)
    .where(
      and(
        eq(users.organizationId, session.organizationId),
        eq(users.isActive, true),
        isNull(users.deletedAt),
      ),
    )
    .orderBy(asc(users.firstName), asc(users.lastName));

  return result;
}

/**
 * Get distinct case stages for filtering.
 */
export async function getCaseStagesForFilter() {
  const session = await requireSession();
  const result = await db
    .select({
      id: caseStages.id,
      name: caseStages.name,
      code: caseStages.code,
    })
    .from(caseStages)
    .where(
      and(
        eq(caseStages.organizationId, session.organizationId),
        isNull(caseStages.deletedAt),
      ),
    )
    .orderBy(asc(caseStages.displayOrder));

  return result;
}
