"use client";

import { useTransition, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { completeTask } from "@/app/actions/tasks";

type Task = {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  dueDate: string | null;
  completedAt: string | null;
  isAutoGenerated: boolean;
  assignedToId: string | null;
  assigneeName: string | null;
  createdAt: string;
};

export function CaseTasksClient({ tasks }: { caseId: string; tasks: Task[] }) {
  const [completedIds, setCompletedIds] = useState<Set<string>>(new Set());
  const [, startTransition] = useTransition();

  const openTasks = tasks.filter(
    (t) =>
      t.status !== "completed" &&
      t.status !== "skipped" &&
      !completedIds.has(t.id),
  );
  const doneTasks = tasks.filter(
    (t) =>
      t.status === "completed" ||
      t.status === "skipped" ||
      completedIds.has(t.id),
  );

  function handleComplete(taskId: string) {
    setCompletedIds((prev) => new Set(prev).add(taskId));
    startTransition(async () => {
      await completeTask(taskId);
    });
  }

  return (
    <div className="space-y-4">
      {openTasks.length === 0 && doneTasks.length === 0 && (
        <div
          className="flex flex-col items-center justify-center py-8 text-center"
          style={{ animation: "emptyStateIn 0.3s ease-out" }}
        >
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[rgba(29,114,184,0.08)]">
            <Checkbox className="pointer-events-none opacity-60" />
          </div>
          <p className="mt-2 text-sm font-medium text-foreground">
            No tasks yet
          </p>
          <p className="mt-0.5 text-xs text-muted-foreground">
            Tasks assigned to this case will appear here
          </p>
        </div>
      )}

      {openTasks.length > 0 && (
        <div className="space-y-1">
          {openTasks.map((task) => (
            <div
              key={task.id}
              className="flex items-start gap-3 rounded-md p-2 hover:bg-accent"
            >
              <Checkbox
                className="mt-0.5"
                onCheckedChange={() => handleComplete(task.id)}
              />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-foreground">
                  {task.title}
                </p>
                <div className="flex items-center gap-2 mt-0.5">
                  {task.assigneeName && (
                    <span className="text-xs text-muted-foreground">
                      {task.assigneeName}
                    </span>
                  )}
                  {task.dueDate && (
                    <span className="text-xs text-muted-foreground">
                      Due {new Date(task.dueDate).toLocaleDateString()}
                    </span>
                  )}
                  {task.isAutoGenerated && (
                    <Badge variant="secondary" className="text-xs py-0">
                      Auto
                    </Badge>
                  )}
                </div>
              </div>
              <Badge
                variant={
                  task.priority === "urgent" || task.priority === "high"
                    ? "destructive"
                    : "outline"
                }
                className="text-xs shrink-0"
              >
                {task.priority}
              </Badge>
            </div>
          ))}
        </div>
      )}

      {doneTasks.length > 0 && (
        <div>
          <p className="text-xs font-medium text-muted-foreground mb-2">
            Completed ({doneTasks.length})
          </p>
          <div className="space-y-1 opacity-60">
            {doneTasks.map((task) => (
              <div
                key={task.id}
                className="flex items-start gap-3 rounded-md p-2"
              >
                <Checkbox checked disabled className="mt-0.5" />
                <div className="min-w-0 flex-1">
                  <p className="text-sm text-muted-foreground line-through">
                    {task.title}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
