import {
  pgTable,
  uuid,
  text,
  timestamp,
  boolean,
  index,
} from "drizzle-orm/pg-core";
import { organizations } from "./organizations";
import { cases } from "./cases";
import { users } from "./users";
import { workflowTemplates, workflowTaskTemplates } from "./workflows";
import { taskStatusEnum, taskPriorityEnum, escalationStateEnum } from "./enums";

export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id),
    caseId: uuid("case_id")
      .notNull()
      .references(() => cases.id),
    title: text("title").notNull(),
    description: text("description"),
    status: taskStatusEnum("status").notNull().default("pending"),
    priority: taskPriorityEnum("priority").notNull().default("medium"),
    assignedToId: uuid("assigned_to_id").references(() => users.id),
    dueDate: timestamp("due_date", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    completedBy: uuid("completed_by").references(() => users.id),

    // Source tracking
    workflowTemplateId: uuid("workflow_template_id").references(
      () => workflowTemplates.id,
    ),
    workflowTaskTemplateId: uuid("workflow_task_template_id").references(
      () => workflowTaskTemplates.id,
    ),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),

    dependsOnTaskId: uuid("depends_on_task_id"),

    // Linkage back to what spawned this task — if the AI created a
    // task from an inbound message or a supervisor event, store the
    // source here for the lifecycle timeline (SA-8, CM-3).
    sourceCommunicationId: uuid("source_communication_id"),
    sourceEventId: uuid("source_event_id"),

    // Escalation state — drives the 3-tier ladder (SA-7). Flipped by
    // the overdue-task sweeper cron.
    escalationState: escalationStateEnum("escalation_state")
      .notNull()
      .default("none"),
    lastEscalatedAt: timestamp("last_escalated_at", { withTimezone: true }),

    // For client-confirmation tasks (CM-3): did we already ask the
    // client whether they'd done this? When did they answer?
    clientConfirmationAskedAt: timestamp("client_confirmation_asked_at", {
      withTimezone: true,
    }),
    clientConfirmationAnsweredAt: timestamp("client_confirmation_answered_at", {
      withTimezone: true,
    }),
    clientConfirmationAnswer: text("client_confirmation_answer"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    index("idx_tasks_org").on(table.organizationId),
    index("idx_tasks_case").on(table.caseId),
    index("idx_tasks_assigned").on(table.assignedToId),
    index("idx_tasks_assigned_status").on(table.assignedToId, table.status),
    index("idx_tasks_assigned_due").on(
      table.assignedToId,
      table.status,
      table.dueDate,
    ),
    index("idx_tasks_case_status").on(table.caseId, table.status),
    index("idx_tasks_org_status").on(table.organizationId, table.status),
  ],
);
