import "server-only";

import { db } from "@/db/drizzle";
import {
  workflowTemplates,
  workflowTaskTemplates,
  tasks,
  caseAssignments,
  auditLog,
} from "@/db/schema";
import { eq, and, isNull } from "drizzle-orm";
import { logger } from "@/lib/logger/server";

/**
 * Add business days to a date, skipping weekends.
 */
function addBusinessDays(date: Date, days: number): Date {
  const result = new Date(date);
  let added = 0;
  while (added < days) {
    result.setDate(result.getDate() + 1);
    const dow = result.getDay();
    if (dow !== 0 && dow !== 6) {
      added++;
    }
  }
  return result;
}

/**
 * Add calendar days to a date.
 */
function addCalendarDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

type Assignment = typeof caseAssignments.$inferSelect;
type TaskTemplate = typeof workflowTaskTemplates.$inferSelect;

/**
 * Resolve the assignee for a workflow task template.
 *
 * Priority:
 * 1. Specific user ID on the template
 * 2. Match by role from case assignments
 * 3. Match by team from case assignments (requires user join)
 * 4. null (unassigned)
 */
function resolveAssignee(
  template: TaskTemplate,
  assignments: Assignment[],
): string | null {
  // Direct user assignment
  if (template.assignToUserId) {
    return template.assignToUserId;
  }

  // Role-based assignment from case assignments
  if (template.assignToRole) {
    const match = assignments.find((a) => a.role === template.assignToRole);
    if (match) return match.userId;
  }

  // No assignee resolved
  return null;
}

export type WorkflowExecutionResult = {
  workflowId: string;
  workflowName: string;
  tasksCreated: number;
  taskIds: string[];
};

/**
 * Execute all active workflows triggered by entering a stage.
 *
 * This is the core automation engine — called when a case stage changes.
 * It finds all workflow templates triggered by the new stage,
 * creates tasks from their task templates, and resolves assignees.
 */
export async function executeStageWorkflows(
  caseId: string,
  newStageId: string,
  triggeredByUserId: string,
  organizationId: string,
): Promise<WorkflowExecutionResult[]> {
  const results: WorkflowExecutionResult[] = [];

  // 1. Find all active workflows triggered by entering this stage
  const workflows = await db
    .select()
    .from(workflowTemplates)
    .where(
      and(
        eq(workflowTemplates.triggerType, "stage_enter"),
        eq(workflowTemplates.triggerStageId, newStageId),
        eq(workflowTemplates.isActive, true),
      ),
    );

  if (workflows.length === 0) {
    logger.info("No workflows triggered for stage", {
      caseId,
      stageId: newStageId,
    });
    return results;
  }

  // 2. Get active case assignments for role-based resolution
  const assignments = await db
    .select()
    .from(caseAssignments)
    .where(
      and(
        eq(caseAssignments.caseId, caseId),
        isNull(caseAssignments.unassignedAt),
      ),
    );

  for (const workflow of workflows) {
    // 3. Get task templates for this workflow
    const taskTemplates = await db
      .select()
      .from(workflowTaskTemplates)
      .where(eq(workflowTaskTemplates.workflowTemplateId, workflow.id))
      .orderBy(workflowTaskTemplates.displayOrder);

    // 4. Create tasks from templates
    const createdTaskIds: Record<string, string> = {};
    const taskIds: string[] = [];

    for (const template of taskTemplates) {
      const assigneeId = resolveAssignee(template, assignments);

      const dueDate = template.dueBusinessDaysOnly
        ? addBusinessDays(new Date(), template.dueDaysOffset)
        : addCalendarDays(new Date(), template.dueDaysOffset);

      // Resolve dependency to previously created task
      const dependsOnTaskId = template.dependsOnTemplateId
        ? (createdTaskIds[template.dependsOnTemplateId] ?? null)
        : null;

      const [newTask] = await db
        .insert(tasks)
        .values({
          organizationId,
          caseId,
          title: template.title,
          description: template.description,
          status: dependsOnTaskId ? "blocked" : "pending",
          priority: template.priority,
          assignedToId: assigneeId,
          dueDate,
          workflowTemplateId: workflow.id,
          workflowTaskTemplateId: template.id,
          isAutoGenerated: true,
          dependsOnTaskId,
          createdBy: triggeredByUserId,
        })
        .returning();

      createdTaskIds[template.id] = newTask.id;
      taskIds.push(newTask.id);
    }

    // 5. Log the workflow execution
    await db.insert(auditLog).values({
      organizationId,
      userId: triggeredByUserId,
      entityType: "workflow",
      entityId: workflow.id,
      action: "workflow_executed",
      changes: {
        caseId,
        stageId: newStageId,
        tasksCreated: taskIds.length,
        taskIds,
      },
    });

    results.push({
      workflowId: workflow.id,
      workflowName: workflow.name,
      tasksCreated: taskIds.length,
      taskIds,
    });

    logger.info("Workflow executed", {
      workflowId: workflow.id,
      workflowName: workflow.name,
      caseId,
      tasksCreated: taskIds.length,
    });
  }

  return results;
}

/**
 * Preview what workflows would fire for a stage transition.
 * Used in the confirmation dialog before a stage change.
 */
export async function previewStageWorkflows(newStageId: string): Promise<
  Array<{
    id: string;
    name: string;
    description: string | null;
    taskCount: number;
    tasks: Array<{
      title: string;
      assignToTeam: string | null;
      dueDaysOffset: number;
    }>;
  }>
> {
  const workflows = await db
    .select()
    .from(workflowTemplates)
    .where(
      and(
        eq(workflowTemplates.triggerType, "stage_enter"),
        eq(workflowTemplates.triggerStageId, newStageId),
        eq(workflowTemplates.isActive, true),
      ),
    );

  const previews = [];

  for (const workflow of workflows) {
    const taskTemplates = await db
      .select()
      .from(workflowTaskTemplates)
      .where(eq(workflowTaskTemplates.workflowTemplateId, workflow.id))
      .orderBy(workflowTaskTemplates.displayOrder);

    previews.push({
      id: workflow.id,
      name: workflow.name,
      description: workflow.description,
      taskCount: taskTemplates.length,
      tasks: taskTemplates.map((t) => ({
        title: t.title,
        assignToTeam: t.assignToTeam,
        dueDaysOffset: t.dueDaysOffset,
      })),
    });
  }

  return previews;
}

/**
 * Unblock tasks that depended on a completed task.
 * Called after a task is completed.
 */
export async function unblockDependentTasks(
  completedTaskId: string,
): Promise<number> {
  const dependentTasks = await db
    .select()
    .from(tasks)
    .where(
      and(
        eq(tasks.dependsOnTaskId, completedTaskId),
        eq(tasks.status, "blocked"),
      ),
    );

  if (dependentTasks.length === 0) return 0;

  await db
    .update(tasks)
    .set({ status: "pending", updatedAt: new Date() })
    .where(
      and(
        eq(tasks.dependsOnTaskId, completedTaskId),
        eq(tasks.status, "blocked"),
      ),
    );

  logger.info("Unblocked dependent tasks", {
    completedTaskId,
    unblockedCount: dependentTasks.length,
  });

  return dependentTasks.length;
}
