"use client";

import { useState, useTransition } from "react";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { completeTask } from "@/app/actions/tasks";
import { CheckCircle, Clock, AlertTriangle } from "lucide-react";
import Link from "next/link";

type QueueTask = {
	id: string;
	title: string;
	description: string | null;
	status: string;
	priority: string;
	dueDate: string | null;
	isAutoGenerated: boolean;
	caseId: string;
	caseNumber: string;
	stageName: string | null;
	stageCode: string | null;
	stageGroupColor: string | null;
	createdAt: string;
};

type Counts = {
	all: number;
	overdue: number;
	today: number;
	thisWeek: number;
	nextWeek: number;
	noDate: number;
};

function getDueDateInfo(dueDate: string | null) {
	if (!dueDate) return { label: "No date", color: "text-muted-foreground" };
	const due = new Date(dueDate);
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const tomorrow = new Date(today);
	tomorrow.setDate(tomorrow.getDate() + 1);

	if (due < now) return { label: "Overdue", color: "text-red-600" };
	if (due < tomorrow) return { label: "Today", color: "text-amber-600" };

	const diff = Math.ceil((due.getTime() - today.getTime()) / 86400000);
	if (diff === 1) return { label: "Tomorrow", color: "text-foreground" };
	if (diff <= 7)
		return {
			label: due.toLocaleDateString("en-US", { weekday: "short" }),
			color: "text-muted-foreground",
		};
	return {
		label: due.toLocaleDateString("en-US", {
			month: "short",
			day: "numeric",
		}),
		color: "text-muted-foreground",
	};
}

export function QueueClient({
	initialTasks,
	counts,
}: {
	initialTasks: QueueTask[];
	counts: Counts;
}) {
	const [activeTab, setActiveTab] = useState("all");
	const [completedIds, setCompletedIds] = useState<Set<string>>(new Set());
	const [, startTransition] = useTransition();

	const filteredTasks = initialTasks.filter((task) => {
		if (completedIds.has(task.id)) return false;
		if (activeTab === "all") return true;
		if (activeTab === "overdue") {
			return task.dueDate && new Date(task.dueDate) < new Date();
		}
		if (activeTab === "today") {
			if (!task.dueDate) return false;
			const due = new Date(task.dueDate);
			const now = new Date();
			const today = new Date(
				now.getFullYear(),
				now.getMonth(),
				now.getDate(),
			);
			const tomorrow = new Date(today);
			tomorrow.setDate(tomorrow.getDate() + 1);
			return due >= today && due < tomorrow;
		}
		if (activeTab === "no_date") return !task.dueDate;
		return true;
	});

	function handleComplete(taskId: string) {
		setCompletedIds((prev) => new Set(prev).add(taskId));
		startTransition(async () => {
			await completeTask(taskId);
		});
	}

	return (
		<div className="space-y-4">
			<Tabs value={activeTab} onValueChange={setActiveTab}>
				<TabsList>
					<TabsTrigger value="all">
						All {counts.all}
					</TabsTrigger>
					<TabsTrigger value="overdue" className="text-red-600">
						Overdue {counts.overdue}
					</TabsTrigger>
					<TabsTrigger value="today" className="text-amber-600">
						Today {counts.today}
					</TabsTrigger>
					<TabsTrigger value="this_week">
						This Week {counts.thisWeek}
					</TabsTrigger>
					<TabsTrigger value="no_date">
						No Date {counts.noDate}
					</TabsTrigger>
				</TabsList>
			</Tabs>

			<div className="rounded-md border">
				{filteredTasks.length === 0 ? (
					<div className="flex flex-col items-center justify-center py-12 text-center">
						<CheckCircle className="h-10 w-10 text-gray-300" />
						<h3 className="mt-3 text-sm font-medium text-foreground">
							All caught up!
						</h3>
						<p className="mt-1 text-sm text-muted-foreground">
							No tasks in this view.
						</p>
					</div>
				) : (
					<div className="divide-y">
						{filteredTasks.map((task) => {
							const dueDateInfo = getDueDateInfo(task.dueDate);
							return (
								<div
									key={task.id}
									className="flex items-start gap-3 p-3 hover:bg-accent transition-colors"
								>
									<Checkbox
										className="mt-1"
										onCheckedChange={() =>
											handleComplete(task.id)
										}
									/>
									{task.priority === "urgent" ||
									task.priority === "high" ? (
										<AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />
									) : (
										<div className="w-4 shrink-0" />
									)}
									<div className="min-w-0 flex-1">
										<p className="text-sm font-medium text-foreground">
											{task.title}
										</p>
										<div className="flex items-center gap-2 mt-0.5">
											<Link
												href={`/cases/${task.caseId}`}
												className="text-xs text-primary hover:underline"
											>
												{task.caseNumber}
											</Link>
											{task.stageName && (
												<Badge
													variant="outline"
													className="text-xs py-0"
													style={{
														borderColor:
															task.stageGroupColor ??
															undefined,
														color:
															task.stageGroupColor ??
															undefined,
													}}
												>
													{task.stageName}
												</Badge>
											)}
											{task.isAutoGenerated && (
												<Badge
													variant="secondary"
													className="text-xs py-0"
												>
													Auto
												</Badge>
											)}
										</div>
									</div>
									<div className="flex items-center gap-1 shrink-0">
										<Clock className="h-3 w-3 text-muted-foreground" />
										<span
											className={`text-xs font-medium ${dueDateInfo.color}`}
										>
											{dueDateInfo.label}
										</span>
									</div>
								</div>
							);
						})}
					</div>
				)}
			</div>
		</div>
	);
}
