"use client";

import { useState, useTransition, useMemo, useEffect, useCallback, useRef } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
	Sheet,
	SheetContent,
	SheetHeader,
	SheetTitle,
	SheetDescription,
	SheetFooter,
} from "@/components/ui/sheet";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import {
	completeTask,
	bulkCompleteTasks,
	reassignTask,
	snoozeTask,
} from "@/app/actions/tasks";
import { HugeiconsIcon } from "@hugeicons/react";
import {
	CheckmarkCircle01Icon,
	Clock01Icon,
	Alert01Icon,
} from "@hugeicons/core-free-icons";
import Link from "next/link";

type QueueTask = {
	id: string;
	title: string;
	description: string | null;
	status: string;
	priority: string;
	dueDate: string | null;
	isAutoGenerated: boolean;
	caseId: string;
	caseNumber: string;
	stageName: string | null;
	stageCode: string | null;
	stageGroupColor: string | null;
	createdAt: string;
};

type TeamQueueTask = QueueTask & {
	assignedToId: string;
	assigneeName: string;
};

type OrgUser = {
	id: string;
	firstName: string;
	lastName: string;
	email: string;
	role: string;
	team: string | null;
};

type CaseStage = {
	id: string;
	name: string;
	code: string;
};

type Counts = {
	all: number;
	overdue: number;
	today: number;
	thisWeek: number;
	nextWeek: number;
	noDate: number;
};

type SortField = "dueDate" | "priority" | "caseName" | "createdAt";

type QueueMode = "my" | "team";

const PRIORITY_ORDER: Record<string, number> = {
	urgent: 0,
	high: 1,
	medium: 2,
	low: 3,
};

function getDueDateInfo(dueDate: string | null) {
	if (!dueDate) return { label: "No date", color: "text-muted-foreground" };
	const due = new Date(dueDate);
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const tomorrow = new Date(today);
	tomorrow.setDate(tomorrow.getDate() + 1);

	if (due < now) return { label: "Overdue", color: "text-red-600" };
	if (due < tomorrow) return { label: "Today", color: "text-amber-600" };

	const diff = Math.ceil((due.getTime() - today.getTime()) / 86400000);
	if (diff === 1) return { label: "Tomorrow", color: "text-foreground" };
	if (diff <= 7)
		return {
			label: due.toLocaleDateString("en-US", { weekday: "short" }),
			color: "text-muted-foreground",
		};
	return {
		label: due.toLocaleDateString("en-US", {
			month: "short",
			day: "numeric",
		}),
		color: "text-muted-foreground",
	};
}

function formatFullDate(dateStr: string | null): string {
	if (!dateStr) return "No due date";
	return new Date(dateStr).toLocaleDateString("en-US", {
		weekday: "long",
		month: "long",
		day: "numeric",
		year: "numeric",
	});
}

function getEndOfWeek(): Date {
	const now = new Date();
	const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const endOfWeek = new Date(today);
	endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
	return endOfWeek;
}

function getEndOfNextWeek(): Date {
	const endOfWeek = getEndOfWeek();
	const endOfNextWeek = new Date(endOfWeek);
	endOfNextWeek.setDate(endOfNextWeek.getDate() + 7);
	return endOfNextWeek;
}

function isInNextWeek(dueDate: string | null): boolean {
	if (!dueDate) return false;
	const due = new Date(dueDate);
	const endOfWeek = getEndOfWeek();
	const endOfNextWeek = getEndOfNextWeek();
	return due >= endOfWeek && due <= endOfNextWeek;
}

export function QueueClient({
	initialTasks,
	counts,
	isManager,
	teamTasks,
	orgUsers,
	caseStages,
}: {
	initialTasks: QueueTask[];
	counts: Counts;
	isManager: boolean;
	teamTasks: TeamQueueTask[];
	orgUsers: OrgUser[];
	caseStages: CaseStage[];
}) {
	const [queueMode, setQueueMode] = useState<QueueMode>("my");
	const [activeTab, setActiveTab] = useState("all");
	const [completedIds, setCompletedIds] = useState<Set<string>>(new Set());
	const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
	const [selectedTask, setSelectedTask] = useState<QueueTask | null>(null);
	const [sortField, setSortField] = useState<SortField>("dueDate");
	const [focusedIndex, setFocusedIndex] = useState<number>(-1);
	const [stageFilter, setStageFilter] = useState<string>("all");
	const [priorityFilter, setPriorityFilter] = useState<string>("all");
	const [reassignOpen, setReassignOpen] = useState(false);
	const [snoozeCustomOpen, setSnoozeCustomOpen] = useState(false);
	const [snoozeCustomDate, setSnoozeCustomDate] = useState("");
	const [, startTransition] = useTransition();
	const taskListRef = useRef<HTMLDivElement>(null);

	// Determine which tasks to show based on queue mode
	const baseTasks: QueueTask[] = queueMode === "team" ? teamTasks : initialTasks;

	const filteredTasks = useMemo(() => {
		const filtered = baseTasks.filter((task) => {
			if (completedIds.has(task.id)) return false;

			// Stage filter
			if (stageFilter !== "all" && task.stageCode !== stageFilter) return false;

			// Priority filter
			if (priorityFilter !== "all" && task.priority !== priorityFilter) return false;

			// Tab filter
			if (activeTab === "all") return true;
			if (activeTab === "overdue") {
				return task.dueDate && new Date(task.dueDate) < new Date();
			}
			if (activeTab === "today") {
				if (!task.dueDate) return false;
				const due = new Date(task.dueDate);
				const now = new Date();
				const today = new Date(
					now.getFullYear(),
					now.getMonth(),
					now.getDate(),
				);
				const tomorrow = new Date(today);
				tomorrow.setDate(tomorrow.getDate() + 1);
				return due >= today && due < tomorrow;
			}
			if (activeTab === "this_week") {
				if (!task.dueDate) return false;
				const due = new Date(task.dueDate);
				const now = new Date();
				const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
				const endOfWeek = getEndOfWeek();
				return due >= today && due <= endOfWeek;
			}
			if (activeTab === "next_week") {
				return isInNextWeek(task.dueDate);
			}
			if (activeTab === "no_date") return !task.dueDate;
			return true;
		});

		return filtered.sort((a, b) => {
			if (sortField === "dueDate") {
				if (!a.dueDate && !b.dueDate) return 0;
				if (!a.dueDate) return 1;
				if (!b.dueDate) return -1;
				return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
			}
			if (sortField === "priority") {
				return (PRIORITY_ORDER[a.priority] ?? 2) - (PRIORITY_ORDER[b.priority] ?? 2);
			}
			if (sortField === "caseName") {
				return a.caseNumber.localeCompare(b.caseNumber);
			}
			if (sortField === "createdAt") {
				return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
			}
			return 0;
		});
	}, [baseTasks, completedIds, activeTab, sortField, stageFilter, priorityFilter]);

	// Group team tasks by assignee
	const groupedTeamTasks = useMemo(() => {
		if (queueMode !== "team") return null;
		const groups: Record<string, { name: string; tasks: TeamQueueTask[] }> = {};
		for (const task of filteredTasks as TeamQueueTask[]) {
			const key = task.assignedToId || "unassigned";
			if (!groups[key]) {
				groups[key] = {
					name: task.assigneeName || "Unassigned",
					tasks: [],
				};
			}
			groups[key].tasks.push(task);
		}
		return Object.entries(groups).sort(([, a], [, b]) =>
			a.name.localeCompare(b.name),
		);
	}, [filteredTasks, queueMode]);

	function handleComplete(taskId: string) {
		setCompletedIds((prev) => new Set(prev).add(taskId));
		setSelectedIds((prev) => {
			const next = new Set(prev);
			next.delete(taskId);
			return next;
		});
		startTransition(async () => {
			await completeTask(taskId);
		});
	}

	function handleBulkComplete() {
		const ids = Array.from(selectedIds);
		for (const id of ids) {
			setCompletedIds((prev) => new Set(prev).add(id));
		}
		setSelectedIds(new Set());
		startTransition(async () => {
			await bulkCompleteTasks(ids);
		});
	}

	function toggleSelect(taskId: string) {
		setSelectedIds((prev) => {
			const next = new Set(prev);
			if (next.has(taskId)) {
				next.delete(taskId);
			} else {
				next.add(taskId);
			}
			return next;
		});
	}

	function toggleSelectAll() {
		if (selectedIds.size === filteredTasks.length) {
			setSelectedIds(new Set());
		} else {
			setSelectedIds(new Set(filteredTasks.map((t) => t.id)));
		}
	}

	function handleReassign(userId: string) {
		if (!selectedTask) return;
		startTransition(async () => {
			await reassignTask(selectedTask.id, userId);
		});
		setReassignOpen(false);
		setSelectedTask(null);
	}

	function handleSnooze(option: "tomorrow" | "next_week" | "custom", customDate?: string) {
		if (!selectedTask) return;
		let newDate: string;
		if (option === "tomorrow") {
			const d = new Date();
			d.setDate(d.getDate() + 1);
			d.setHours(9, 0, 0, 0);
			newDate = d.toISOString();
		} else if (option === "next_week") {
			const d = new Date();
			d.setDate(d.getDate() + (8 - d.getDay())); // Next Monday
			d.setHours(9, 0, 0, 0);
			newDate = d.toISOString();
		} else {
			if (!customDate) return;
			newDate = new Date(customDate).toISOString();
		}
		startTransition(async () => {
			await snoozeTask(selectedTask.id, newDate);
		});
		setSnoozeCustomOpen(false);
		setSnoozeCustomDate("");
		setSelectedTask(null);
	}

	// Keyboard navigation
	const handleKeyDown = useCallback(
		(e: KeyboardEvent) => {
			// Don't capture keys when sheet is open, or when typing in an input
			if (selectedTask || reassignOpen || snoozeCustomOpen) return;
			const target = e.target as HTMLElement;
			if (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.tagName === "SELECT") return;

			if (e.key === "j") {
				e.preventDefault();
				setFocusedIndex((prev) => Math.min(prev + 1, filteredTasks.length - 1));
			} else if (e.key === "k") {
				e.preventDefault();
				setFocusedIndex((prev) => Math.max(prev - 1, 0));
			} else if (e.key === "x" && focusedIndex >= 0 && focusedIndex < filteredTasks.length) {
				e.preventDefault();
				toggleSelect(filteredTasks[focusedIndex].id);
			} else if (e.key === "Enter" && focusedIndex >= 0 && focusedIndex < filteredTasks.length) {
				e.preventDefault();
				setSelectedTask(filteredTasks[focusedIndex]);
			} else if (e.key === "c" && focusedIndex >= 0 && focusedIndex < filteredTasks.length) {
				e.preventDefault();
				handleComplete(filteredTasks[focusedIndex].id);
			}
		},
		[filteredTasks, focusedIndex, selectedTask, reassignOpen, snoozeCustomOpen],
	);

	useEffect(() => {
		document.addEventListener("keydown", handleKeyDown);
		return () => document.removeEventListener("keydown", handleKeyDown);
	}, [handleKeyDown]);

	// Reset focused index when tasks change
	useEffect(() => {
		setFocusedIndex((prev) => {
			if (prev >= filteredTasks.length) return filteredTasks.length - 1;
			return prev;
		});
	}, [filteredTasks.length]);

	function renderTaskRow(task: QueueTask, index: number) {
		const dueDateInfo = getDueDateInfo(task.dueDate);
		const isFocused = index === focusedIndex;
		return (
			<div
				key={task.id}
				className={`flex items-start gap-3 p-3 hover:bg-accent transition-colors cursor-pointer ${
					isFocused ? "ring-2 ring-primary ring-inset bg-accent/50" : ""
				}`}
				onClick={() => setSelectedTask(task)}
				onKeyDown={(e) => {
					if (e.key === "Enter" || e.key === " ") {
						e.preventDefault();
						setSelectedTask(task);
					}
				}}
				role="button"
				tabIndex={0}
			>
				<Checkbox
					className="mt-1"
					checked={selectedIds.has(task.id)}
					onCheckedChange={() => toggleSelect(task.id)}
					onClick={(e) => e.stopPropagation()}
				/>
				{task.priority === "urgent" ||
				task.priority === "high" ? (
					<HugeiconsIcon
						icon={Alert01Icon}
						size={16}
						color="rgb(245 158 11)"
						className="mt-0.5 shrink-0"
					/>
				) : (
					<div className="w-4 shrink-0" />
				)}
				<div className="min-w-0 flex-1">
					<p className="text-sm font-medium text-foreground">
						{task.title}
					</p>
					<div className="flex items-center gap-2 mt-0.5">
						<Link
							href={`/cases/${task.caseId}`}
							className="text-xs text-primary hover:underline"
							onClick={(e) => e.stopPropagation()}
						>
							{task.caseNumber}
						</Link>
						{task.stageName && (
							<Badge
								variant="outline"
								className="text-xs py-0"
								style={{
									borderColor:
										task.stageGroupColor ??
										undefined,
									color:
										task.stageGroupColor ??
										undefined,
								}}
							>
								{task.stageName}
							</Badge>
						)}
						{task.isAutoGenerated && (
							<Badge
								variant="secondary"
								className="text-xs py-0"
							>
								Auto
							</Badge>
						)}
					</div>
				</div>
				<div className="flex items-center gap-1 shrink-0">
					<HugeiconsIcon
						icon={Clock01Icon}
						size={12}
						className="text-muted-foreground"
					/>
					<span
						className={`text-xs font-medium ${dueDateInfo.color}`}
					>
						{dueDateInfo.label}
					</span>
				</div>
			</div>
		);
	}

	return (
		<div className="space-y-4">
			{/* Team Queue toggle (only for managers/admins) */}
			{isManager && (
				<Tabs value={queueMode} onValueChange={(v) => {
					setQueueMode(v as QueueMode);
					setFocusedIndex(-1);
					setSelectedIds(new Set());
				}}>
					<TabsList>
						<TabsTrigger value="my">My Queue</TabsTrigger>
						<TabsTrigger value="team">Team Queue</TabsTrigger>
					</TabsList>
				</Tabs>
			)}

			<div className="flex items-center justify-between gap-3 flex-wrap">
				<Tabs value={activeTab} onValueChange={setActiveTab}>
					<TabsList>
						<TabsTrigger value="all">
							All {counts.all}
						</TabsTrigger>
						<TabsTrigger value="overdue" className="text-red-600">
							Overdue {counts.overdue}
						</TabsTrigger>
						<TabsTrigger value="today" className="text-amber-600">
							Today {counts.today}
						</TabsTrigger>
						<TabsTrigger value="this_week">
							This Week {counts.thisWeek}
						</TabsTrigger>
						<TabsTrigger value="next_week">
							Next Week {counts.nextWeek}
						</TabsTrigger>
						<TabsTrigger value="no_date">
							No Date {counts.noDate}
						</TabsTrigger>
					</TabsList>
				</Tabs>

				<div className="flex items-center gap-2">
					{/* Stage filter */}
					<Select value={stageFilter} onValueChange={setStageFilter}>
						<SelectTrigger className="w-[160px]">
							<SelectValue placeholder="Stage..." />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="all">All Stages</SelectItem>
							{caseStages.map((stage) => (
								<SelectItem key={stage.id} value={stage.code}>
									{stage.name}
								</SelectItem>
							))}
						</SelectContent>
					</Select>

					{/* Priority filter */}
					<Select value={priorityFilter} onValueChange={setPriorityFilter}>
						<SelectTrigger className="w-[150px]">
							<SelectValue placeholder="Priority..." />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="all">All Priorities</SelectItem>
							<SelectItem value="urgent">Urgent</SelectItem>
							<SelectItem value="high">High</SelectItem>
							<SelectItem value="medium">Medium</SelectItem>
							<SelectItem value="low">Low</SelectItem>
						</SelectContent>
					</Select>

					{/* Sort */}
					<Select value={sortField} onValueChange={(v) => setSortField(v as SortField)}>
						<SelectTrigger className="w-[180px]">
							<SelectValue placeholder="Sort by..." />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="dueDate">Sort by Due Date</SelectItem>
							<SelectItem value="priority">Sort by Priority</SelectItem>
							<SelectItem value="caseName">Sort by Case Name</SelectItem>
							<SelectItem value="createdAt">Sort by Created Date</SelectItem>
						</SelectContent>
					</Select>
				</div>
			</div>

			{/* Bulk Actions Bar */}
			{selectedIds.size > 0 && (
				<div className="flex items-center gap-3 rounded-md border bg-accent px-4 py-2">
					<span className="text-sm font-medium">
						{selectedIds.size} selected
					</span>
					<Separator orientation="vertical" className="h-5" />
					<Button size="sm" variant="default" onClick={handleBulkComplete}>
						<HugeiconsIcon icon={CheckmarkCircle01Icon} size={14} className="mr-1" />
						Complete Selected
					</Button>
					<Button size="sm" variant="outline" onClick={() => setSelectedIds(new Set())}>
						Clear
					</Button>
				</div>
			)}

			<div className="rounded-md border" ref={taskListRef}>
				{filteredTasks.length === 0 ? (
					<div className="flex flex-col items-center justify-center py-12 text-center">
						<HugeiconsIcon
							icon={CheckmarkCircle01Icon}
							size={40}
							color="rgb(209 213 219)"
						/>
						<h3 className="mt-3 text-sm font-medium text-foreground">
							All caught up!
						</h3>
						<p className="mt-1 text-sm text-muted-foreground">
							No tasks in this view.
						</p>
					</div>
				) : queueMode === "team" && groupedTeamTasks ? (
					<div className="divide-y">
						{/* Select all header */}
						<div className="flex items-center gap-3 px-3 py-2 bg-muted/50">
							<Checkbox
								checked={selectedIds.size === filteredTasks.length && filteredTasks.length > 0}
								onCheckedChange={toggleSelectAll}
							/>
							<span className="text-xs text-muted-foreground">
								{filteredTasks.length} task{filteredTasks.length !== 1 ? "s" : ""}
							</span>
						</div>
						{groupedTeamTasks.map(([userId, group]) => {
							// Find global index of first task in this group to maintain correct focus
							const globalStartIndex = filteredTasks.findIndex(
								(t) => t.id === group.tasks[0]?.id,
							);
							return (
								<div key={userId}>
									<div className="bg-muted/30 px-3 py-2 border-b">
										<span className="text-sm font-semibold text-foreground">
											{group.name}
										</span>
										<span className="text-xs text-muted-foreground ml-2">
											({group.tasks.length} task{group.tasks.length !== 1 ? "s" : ""})
										</span>
									</div>
									<div className="divide-y">
										{group.tasks.map((task, localIdx) =>
											renderTaskRow(task, globalStartIndex + localIdx),
										)}
									</div>
								</div>
							);
						})}
					</div>
				) : (
					<div className="divide-y">
						{/* Select all header */}
						<div className="flex items-center gap-3 px-3 py-2 bg-muted/50">
							<Checkbox
								checked={selectedIds.size === filteredTasks.length && filteredTasks.length > 0}
								onCheckedChange={toggleSelectAll}
							/>
							<span className="text-xs text-muted-foreground">
								{filteredTasks.length} task{filteredTasks.length !== 1 ? "s" : ""}
							</span>
						</div>
						{filteredTasks.map((task, index) => renderTaskRow(task, index))}
					</div>
				)}
			</div>

			{/* Keyboard shortcuts help */}
			<div className="flex items-center gap-4 text-xs text-muted-foreground flex-wrap">
				<span>
					<kbd className="rounded border bg-muted px-1 py-0.5 font-mono text-[10px]">j</kbd>
					<kbd className="rounded border bg-muted px-1 py-0.5 font-mono text-[10px] ml-0.5">k</kbd>
					{" "}navigate
				</span>
				<span>
					<kbd className="rounded border bg-muted px-1 py-0.5 font-mono text-[10px]">x</kbd>
					{" "}select
				</span>
				<span>
					<kbd className="rounded border bg-muted px-1 py-0.5 font-mono text-[10px]">Enter</kbd>
					{" "}open details
				</span>
				<span>
					<kbd className="rounded border bg-muted px-1 py-0.5 font-mono text-[10px]">c</kbd>
					{" "}complete
				</span>
			</div>

			{/* Task Detail Sheet */}
			<Sheet open={!!selectedTask && !reassignOpen && !snoozeCustomOpen} onOpenChange={(open) => !open && setSelectedTask(null)}>
				<SheetContent side="right" className="sm:max-w-md">
					{selectedTask && (
						<>
							<SheetHeader>
								<SheetTitle>{selectedTask.title}</SheetTitle>
								<SheetDescription>
									{selectedTask.caseNumber} &middot; {selectedTask.stageName ?? "No stage"}
								</SheetDescription>
							</SheetHeader>

							<div className="mt-6 space-y-5">
								{/* Priority & Status */}
								<div className="flex gap-2">
									<Badge
										variant={
											selectedTask.priority === "urgent"
												? "destructive"
												: selectedTask.priority === "high"
													? "default"
													: "secondary"
										}
									>
										{selectedTask.priority}
									</Badge>
									<Badge variant="outline">{selectedTask.status}</Badge>
									{selectedTask.isAutoGenerated && (
										<Badge variant="secondary">Auto-generated</Badge>
									)}
								</div>

								{/* Due Date */}
								<div>
									<p className="text-xs font-medium text-muted-foreground mb-1">
										Due Date
									</p>
									<div className="flex items-center gap-2">
										<HugeiconsIcon icon={Clock01Icon} size={14} className="text-muted-foreground" />
										<span className={`text-sm ${getDueDateInfo(selectedTask.dueDate).color}`}>
											{formatFullDate(selectedTask.dueDate)}
										</span>
									</div>
								</div>

								{/* Description / Notes */}
								<div>
									<p className="text-xs font-medium text-muted-foreground mb-1">
										Description
									</p>
									<p className="text-sm text-foreground">
										{selectedTask.description || "No description provided."}
									</p>
								</div>

								{/* Case Link */}
								<div>
									<p className="text-xs font-medium text-muted-foreground mb-1">
										Case
									</p>
									<Link
										href={`/cases/${selectedTask.caseId}`}
										className="text-sm text-primary hover:underline"
									>
										{selectedTask.caseNumber} — {selectedTask.stageName}
									</Link>
								</div>

								{/* Stage */}
								{selectedTask.stageName && (
									<div>
										<p className="text-xs font-medium text-muted-foreground mb-1">
											Current Stage
										</p>
										<Badge
											variant="outline"
											style={{
												borderColor: selectedTask.stageGroupColor ?? undefined,
												color: selectedTask.stageGroupColor ?? undefined,
											}}
										>
											{selectedTask.stageCode} — {selectedTask.stageName}
										</Badge>
									</div>
								)}
							</div>

							<SheetFooter className="mt-8 flex flex-col gap-2">
								{/* Complete */}
								<Button
									className="w-full"
									onClick={() => {
										handleComplete(selectedTask.id);
										setSelectedTask(null);
									}}
								>
									<HugeiconsIcon icon={CheckmarkCircle01Icon} size={14} className="mr-1" />
									Complete Task
								</Button>

								<div className="flex gap-2 w-full">
									{/* Reassign */}
									<DropdownMenu>
										<DropdownMenuTrigger asChild>
											<Button variant="outline" className="flex-1">
												Reassign
											</Button>
										</DropdownMenuTrigger>
										<DropdownMenuContent align="start" className="max-h-60 overflow-y-auto">
											{orgUsers.map((user) => (
												<DropdownMenuItem
													key={user.id}
													onClick={() => handleReassign(user.id)}
												>
													{user.firstName} {user.lastName}
													{user.team && (
														<span className="text-muted-foreground ml-1 text-xs">
															({user.team})
														</span>
													)}
												</DropdownMenuItem>
											))}
										</DropdownMenuContent>
									</DropdownMenu>

									{/* Snooze */}
									<DropdownMenu>
										<DropdownMenuTrigger asChild>
											<Button variant="outline" className="flex-1">
												Snooze
											</Button>
										</DropdownMenuTrigger>
										<DropdownMenuContent align="end">
											<DropdownMenuItem
												onClick={() => handleSnooze("tomorrow")}
											>
												Tomorrow
											</DropdownMenuItem>
											<DropdownMenuItem
												onClick={() => handleSnooze("next_week")}
											>
												Next Week
											</DropdownMenuItem>
											<DropdownMenuItem
												onClick={() => {
													setSnoozeCustomOpen(true);
												}}
											>
												Custom Date...
											</DropdownMenuItem>
										</DropdownMenuContent>
									</DropdownMenu>
								</div>
							</SheetFooter>
						</>
					)}
				</SheetContent>
			</Sheet>

			{/* Custom Snooze Date Dialog (using Sheet for consistency) */}
			<Sheet open={snoozeCustomOpen} onOpenChange={(open) => {
				if (!open) {
					setSnoozeCustomOpen(false);
					setSnoozeCustomDate("");
				}
			}}>
				<SheetContent side="right" className="sm:max-w-sm">
					<SheetHeader>
						<SheetTitle>Snooze Until</SheetTitle>
						<SheetDescription>
							Pick a custom date to snooze this task.
						</SheetDescription>
					</SheetHeader>
					<div className="mt-6 space-y-4">
						<Input
							type="date"
							value={snoozeCustomDate}
							onChange={(e) => setSnoozeCustomDate(e.target.value)}
						/>
						<div className="flex gap-2">
							<Button
								className="flex-1"
								disabled={!snoozeCustomDate}
								onClick={() => handleSnooze("custom", snoozeCustomDate)}
							>
								Snooze
							</Button>
							<Button
								variant="outline"
								onClick={() => {
									setSnoozeCustomOpen(false);
									setSnoozeCustomDate("");
								}}
							>
								Cancel
							</Button>
						</div>
					</div>
				</SheetContent>
			</Sheet>
		</div>
	);
}
